<?php $image = $block->getConfigBanner();
      $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
      $params = $this->getRequest()->getParams();
      $productPrices = $block->getProductPrices();
      $roomPrices = $block->getRoomPrices();
      
      $_baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                               ->getStore()
                               ->getBaseUrl();
      $urlsearch = $_baseUrl.'booking/booking/searchbooking';
      $helper = $objectManager->create('Ced\Booking\Helper\Booking\Image');
      $Datahelper = $objectManager->create('Ced\Booking\Helper\Data');
      $configwidth = $Datahelper->getStoreConfigValue('booking/banner_setting/banner_width');
      $configheight = $Datahelper->getStoreConfigValue('booking/banner_setting/banner_height');
      $mapApiKey = $Datahelper->getStoreConfigValue('booking/booking_config/map_api_key');
      $isEnableTopFilter = $Datahelper->getStoreConfigValue('booking/Filter_setting/enable_top_filter');
      $placeholder = $block->getViewFileUrl('Magento_Catalog::images/product/placeholder/image.jpg');
      $width = $configwidth != ''? $configwidth : 800;
      $height= $configheight != ''? $configheight : 200;  

        $address = $this->getRequest()->getParam('address');
        $searchByAddress = $this->getRequest()->getParam('search_by_address');
        $checkIn = $this->getRequest()->getParam('check_in');
        $checkOut = $this->getRequest()->getParam('check_out');
        $searchByRooms = $this->getRequest()->getParam('search_by_rooms');
        $searchByPrice = $this->getRequest()->getParam('search_by_price');
        $action = $this->getCurrentPage();
        $currency = $block->getCurrencySymbol();
        $currentCorrencyCode = $block->getCurrentCode();
        $currencyModel = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currentCorrencyCode);
        $currencySymbol = $currencyModel->getCurrencySymbol();
 
        $currentAction = $this->getCurrentPage();
        $totalNum = 4;
        if($currentAction == 'hotel'){
            $totalNum = 5;
            $minPrice = count($roomPrices)!=0 ? min($roomPrices) : 0;
            $maxPrice = count($roomPrices)!=0 ? max($roomPrices) : 100;
        } else {
            $minPrice = count($productPrices)!=0 ? min($productPrices) : 0;
            $maxPrice = count($productPrices)!=0 ? max($productPrices) : 100;
        }
        $url =  "booking/bookings/".$currentAction;
      ?>

<div>
    <p>
        <img id="booking-banner"
             src="<?php echo $helper->resize($image,$width,$height,$placeholder);  ?>"
              alt="Booking Banner" height="100%" width="100%" /> 
    </p>
    <?php if ($isEnableTopFilter) : ?>
    <div>
        <form id="search-form" class=""booking_search" action="<?php echo $this->getFormActionUrl(); ?>">
            <input type="hidden" value="<?php echo $address; ?>" name="address" id="address"></input>
            <div class="booking-search-wrapper col-<?php echo $totalNum; ?>">
                <div class="col">
                    <label for="price">Filter By Price :</label>
                    <input type="text" id="price" name="search_by_price" readonly style="border:0; color:#006bb4; font-weight:bold;">
                    <div id="price-range-slider"></div>
                </div>
                <div class="col">
                    <i class="fa fa-map-marker input-icon"></i>
                    <input id="searchByaddress" value="<?php echo $searchByAddress; ?>" name="search_by_address" type="text" placeholder="<?php echo __('Location') ?>" value="">
                </div>
                <?php if($currentAction=="hotel"){  ?>
                <div class="col">
                    <div class="col-2">
                        <div class="col">
                            <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                            <input  value="<?php echo $checkIn; ?>" type="text" id="hotel-check-in" name="check_in" placeholder="<?php echo __('Check In') ?>" value="" class="form-control" readOnly=true>
                        </div>
                        <div class="col">
                            <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                            <input value="<?php echo $checkOut; ?>" type="text" id="hotel-check-out" name="check_out" placeholder="<?php echo __('Check Out') ?>" value=""class="form-control" readOnly=true>
                        </div>
                    </div>
                </div>
                <?php } else { ?>
                <div class="col">
                    <div class="col-2">
                        <div class="col">
                            <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                            <input  value="<?php echo $checkIn; ?>" type="text" id="check-in" name="check_in" placeholder="<?php echo __('Check In') ?>" value="" class="form-control" readOnly=true>
                        </div>
                        <div class="col">
                            <i class="fa fa-calendar input-icon input-icon-highlight"></i>
                            <input value="<?php echo $checkOut; ?>" type="text" id="check-out" name="check_out" placeholder="<?php echo __('Check Out') ?>" value=""class="form-control" readOnly=true>
                        </div>
                    </div>
                </div>
                <?php } ?>
                <!-- <div class="col">
                    <?php
                    $priceList = [];
                    $priceList[] = '0-100';
                    $priceList[] = '100-200';
                    $priceList[] = '200-300';
                    $priceList[] = '300-400';
                    $priceList[] = '400-500';
                    $priceList[] = '500-And More';

                    ?>
                    <select id="price" name="search_by_price">
                        <option value=""><?php echo __('--Choose Price--') ?></option>
                        <?php foreach ($priceList as $price) { 
                                $selected = ($price==$searchByPrice)?'selected="selected"':'';
                            ?>
                            <option <?php echo $selected; ?>><?php echo $price;?></option>
                        <?php } ?>
                    </select>
                </div> -->
                <div class="col">
                    <div class="actions">
                        <button class="action subscribe primary" title="Search" type="submit">
                            <span><?php echo __('Search') ?></span>
                        </button>
                    </div>

                </div> 
                
                <div style="clear:both;"></div>
            </div>
        </form>
         <div class="col">
                    <div class="reset-filter-action">
                        <button id="reset-filter" class="action subscribe reset-Filter-btn" title="Reset Filter" type="Button">
                            <span><?php echo __('Reset Filter') ?></span>
                        </button>
                    </div>

                </div>
        <?php /*
        <div id="product-lists" style="clear:both;">
            <?php echo $this->getLayout()->createBlock('Ced\Booking\Block\BookingFilter')->setTemplate('Ced_Booking::filter.phtml')->toHtml();?>
        </div>
        <div id="searched-product-lists"></div>
        */ ?>
    </div>
<?php endif; ?>
</div>

<!-- <script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&language=en"></script> -->
<script src="http://maps.googleapis.com/maps/api/js?v=3&key=<?php echo $mapApiKey; ?>&sensor=false&libraries=places"></script>

<script>
    require([
        'jquery',
        "jquery/ui"
        ],
        function ($){

            var input = document.getElementById('searchByaddress');
            var autocomplete = new google.maps.places.Autocomplete(input,{types: ['(cities)']});
            google.maps.event.addListener(autocomplete, 'place_changed', function(){
                var place = autocomplete.getPlace();
                document.getElementById('address').value = place.address_components[0].long_name;

            });

            $( "#searchByaddress" ).keyup(function() {
              $('#address').val($('#searchByaddress').val());
            }); 

            var dateToday = new Date();

            $( "#check-in, #check-out" ).datepicker({
                minDate: dateToday,
                dateFormat: "yy-mm-dd",
                onSelect: function( selectedDate, inst) {
                    var date = jQuery.datepicker.parseDate(inst.settings.dateFormat || jQuery.datepicker._defaults.dateFormat, selectedDate, inst.settings);
                    var dateText = jQuery.datepicker.formatDate("yy-mm-dd", date, inst.settings);
                    if(this.id == "check-in"){                                        
                        date.setDate(date.getDate());
                        jQuery("#check-out" ).datepicker( "option", "minDate", date );
                    }
                    
                }
            });

            $( "#hotel-check-in, #hotel-check-out" ).datepicker({
                minDate: dateToday,
                dateFormat: "yy-mm-dd",
                onSelect: function( selectedDate, inst) {
                    var date = jQuery.datepicker.parseDate(inst.settings.dateFormat || jQuery.datepicker._defaults.dateFormat, selectedDate, inst.settings);
                    var dateText = jQuery.datepicker.formatDate("yy-mm-dd", date, inst.settings);
                    if(this.id == "hotel-check-in"){                                        
                        date.setDate(date.getDate()+1);
                        jQuery("#hotel-check-out" ).datepicker( "option", "minDate", date );
                    }
                    
                }
            });
            var currentUrl = "<?php echo $this->getUrl($url); ?>";

            $('#reset-filter').click(function(){
                window.location.href = currentUrl;
            });

            var currencySymbol = "<?php echo $currencySymbol; ?>";

                $( "#price-range-slider" ).slider({
                    range: true,
                    min: 0,
                    max: <?php echo $maxPrice;?>,
                    values: [ <?php echo $minPrice; ?>, <?php echo $maxPrice; ?> ],
                    slide: function( event, ui ) {
                        $( "#price" ).val( currencySymbol + ui.values[ 0 ] + " - "+currencySymbol + ui.values[ 1 ] );
                    }
                });
                $( "#price" ).val( currencySymbol + $( "#price-range-slider" ).slider( "values", 0 ) +
                    " - "+currencySymbol + $( "#price-range-slider" ).slider( "values", 1 ) );
        });
</script>
<?php /** code for listing of the products **/ ?>
<?php /** code for listing of the products **/ ?>
<?php /** code for listing of the products **/ ?>
<?php /** code for listing of the products **/ ?>
<?php /** code for listing of the products **/ ?>



<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php
$_productCollection = $block->getLoadedProductCollection();

//$helper_data=$this->helper('Ced\CsMarketplace\Helper\Data');
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php //if($this->helper('Ced\CsMarketplace\Helper\Acl')->isEnabled()) { ?>

    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('There are no products for this booking.') ?></div></div>
    <?php else: ?>
        <?php echo $block->getToolbarHtml() ?>
        <?php echo $block->getAdditionalHtml() ?>
        <?php
        if ($block->getMode() == 'grid') {
            $viewMode = 'grid';
            $image = 'category_page_grid';
            $showDescription = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        } else {
            $viewMode = 'list';
            $image = 'category_page_list';
            $showDescription = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
        }
        /**
         * Position for actions regarding image size changing in vde if needed
         */
        $pos = $block->getPositioned();
        ?>
        <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
            <?php $iterator = 1; ?>
            <?php // Vendor Logo
            // $width = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_width',$this->getCurrentStoreId());
            // $height = (int)$helper_data->getStoreConfig('ced_vshops/general/list_image_height',$this->getCurrentStoreId());
            $width = 135;
            $height = 135;
            ?>
            <ol class="products list items product-items">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($_productCollection as $_product): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info" data-container="product-grid">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?php echo $productImage->toHtml(); ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            </strong>
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            <?php if ($currentAction == 'hotel') : ?>
                                <span class='hotel-min-price'><?php /* @escapeNotVerified */ echo __('Starting From: ').' '.$currency->currency($block->getProductPrice($_product)); ?></span>
                            <?php else: ?>
                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                            <?php endif; ?>
                            <?php echo $block->getProductDetailsHtml($_product); ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <?php if (count($params)!=0 && isset($params['check_in'])) { ?>
                                                    <button onclick="setLocation('<?php echo $_product->getProductUrl().'/?check_in='.$params['check_in'].'&check_out='.$params['check_out']; ?>')" type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Book Now')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Book Now') ?></span>
                                                    </button>
                                                <?php } else { ?>
                                                    <button onclick="setLocation('<?php echo $_product->getProductUrl() ?>')" type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Book Now')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Book Now') ?></span>
                                                    </button>
                                                <?php } ?>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                        </a>
                                    </div>
                                </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                <?php endforeach; ?>
            </ol>
        </div>
        <?php echo $block->getToolbarHtml() ?>
        <?php if (!$block->isRedirectToCartEnabled()) : ?>
            <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
        <?php endif; ?>
    <?php endif; ?>
<?php //} ?>
<script>
    function setLocation(url){
        window.location.href = url;
    }
</script>




