<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the 
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category  Ced
 * @package   Ced_Booking
 * @author    CedCommerce Magento Core Team <Ced_MagentoCoreTeam@cedcommerce.com>
 * @copyright Copyright CedCommerce (http://cedcommerce.com/)
 * @license   http://cedcommerce.com/license-agreement.txt  
 * 
 */

?>


<?php

$room_id=$this->getRequest()->getParam('Room_Id');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$roomNumberModel=$objectManager->create('Ced\Booking\Model\RoomNumbers')->getCollection()->addFieldToFilter('room_id',$room_id)->getData();
$data = json_encode($roomNumberModel);

?>


<fieldset id="room_numbers_block" class="fieldset">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Manage Room Availability)') ?></span></legend>

    <div id="manage-room-numbers-options-panel" >

        <table class="admin__control-table">

            <thead>

                <tr id="room-numbers-options-table">

                    <th class="col-draggable"></th>

                    <th class="col-default control-table-actions-th"><?php echo __('Room Number');?></th>
                    <!-- <th class="col-default control-table-actions-th"><?php //echo __('To-period');?></th> -->

                    <th class="col-delete">&nbsp;</th>

                </tr>

            </thead>

            <tbody data-role="room-number-options-container" class="ignore-validate">            
            </tbody>
            <tfoot>

            <tr>

                <th colspan="<?php /* @escapeNotVerified */ //echo $storetotal; ?>" class="col-actions-add">

                    <?php // if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>

                        <button id="add_new_room_number_button" title="<?php /* @escapeNotVerified */ echo __('Add Option'); ?>"

                            type="button" class="action- scalable add">

                             <span><?php /* @escapeNotVerified */ echo __('Add Option'); ?></span>

                        </button>

                    <?php //endif; ?>

                </th>

            </tr>

     		<tr>

               

            </tr>

            </tfoot>

        </table>

        <input type="hidden" id="room-number-count-check" value="" />

    </div>

    <script id="room-number-row-template" type="text/x-magento-template">
    
         <tr>

            <td class="col-draggable">

                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>

                    <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */ echo __('Sort Option'); ?>"></div>

                <?php endif; ?>

                <input data-role="room-order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?> disabled="disabled"<?php endif; ?>/>

            </td>

                <!-- <td class="col-default control-table-actions-cell">

                    <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %><?php //if ($block->getReadOnly()):?>disabled="disabled"<?php //endif;?>/>

                </td> -->

                <td class="col-default control-table-actions-cell">
                    <input name="room_number_<%- data.id %>" value="<%- data.room_number %>" class="input-text room-number"/>
                </td>

                <!-- <td class="col-default control-table-actions-cell">
                    <input tye="text" name="to-period" value="" class="input-text to-date"/>
                </td> -->

                <td id="delete_button_container_<%- data.id %>" class="col-delete">

                    <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />

                    <?php //if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>

                        <button id="delete_button_<%- data.id %>" title="<?php /* @escapeNotVerified */ echo __('Delete') ?>" type="button"

                            class="action- scalable delete delete-option"

                            >

                            <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>

                        </button>

                    <?php //endif;?>

                </td>
           

        </tr>

    </script>

   <?php

     if(count($roomNumberModel)!=0) { 
        foreach ($roomNumberModel as $room) { 

            $values[] = [ 'checked'=>'',
                          'intype' => 'radio',
                          'id' => 'edit_'.$room['id'],
                          'sort_order' =>$room['id'],
                          'room_number' => $room['room_numbers']
                        ];
        }
    } else {
        $values = [];
    }

?>

    

    <script type="text/x-magento-init">

        {

            "*": {

                "Ced_Booking/js/edit_room_options": {

                    "attributesData":<?php /* @noEscape */ echo json_encode($values, JSON_HEX_QUOT); ?>,

                    "isSortable":  <?php echo (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()) ?>,

                    "isReadOnly": <?php echo (int)$block->getReadOnly(); ?>

                }

            }

        }

    </script>
</fieldset>


