<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
 <?php $_product = $block->getProduct(); ?>
<?php 
if(!$_product)
{
	$_product = $this->getBookingProduct();
}
 ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php //if ($_product->isSaleable()): ?>  
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button type="submit"
                    disabled="disabled"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-addtocart-button">
                <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
            </button>
        </div>
    </div>
</div>
  <?php //endif; ?>
<?php //if ($block->isRedirectToCartEnabled()) : echo "if";?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": true
            }
        }
    }
</script>
<script>
require([
            'jquery'
        ],
    function ($){

        
            $('#product-addtocart-button').click(function(){

                setTimeout(function(){
            
                    $('#product-addtocart-button').prop('disabled',true);
                    $('#room-popup-wrapper').trigger('closeModal');
                },8000);
            });
        
        
    });
</script>