<?php 
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('Ced\Booking\Helper\Data');
$roomCategories = $helper->getRoomCategories();
$roomTypesData = $helper->getRoomTypes();
$roomCategoryData = $helper->getRoomCategories();
$rooms_data = $block->getRoomsData(); 
$product = $block->getProduct();
$roomImages = $block->getroomsimage();
$currencySymbol = $block->getCurrenySymbol();
$roomAmenities = $block->getRoomsFacilitiyRelation();
$facilities = $helper->getFacilities();
$productId = $block->getProductId();

$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey'); 

$mediaUrl = $objectManager->create('\Magento\Store\Model\StoreManagerInterface')
			  ->getStore()
			  ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
$_baseUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
						->getStore()
						->getBaseUrl();

$checkAvailbilityUrl = $_baseUrl.'booking/booking/checkroomavailability';
$CartUrl = $_baseUrl.'checkout/cart/add';

$title = '';
$roomCategory = '';
$price = '';
$countRoomNumbers = [];
$roomId = '';
$price = '';
$roomDesc = '';
$maxAllowedAdults = '';
$maxAllowedchild = '';

foreach ($rooms_data as $data) {
	$roomDesc = $data['description'] !='' ? $data['description'] : 'Room description is empty';
	
	if ($data['room_numbers'] != '') {
		$countRoomNumbers[] = $data['room_numbers'];
	}
	
	foreach ($roomTypesData as $type) {
		if ($type->getId()==$data['room_type_id'])
		{
			$title = $type->getTitle();
			$maxAllowedAdults = $type->getMinAllowedChild() !='' ? $type->getMinAllowedChild() : '';
			$maxAllowedchild = $type->getMaxAllowedChild() !='' ? $type->getMaxAllowedChild() : '';
		}
	}
	foreach ($roomCategoryData as $category) {
		if ($category->getId()==$data['room_category_id'])
		{
			$roomCategory = $category->getTitle();
		}
	}
	$roomId = $data['id'];
	$price = $data['price'];

}
$Datahelper = $objectManager->create('Ced\Booking\Helper\Data');
$isCalendarEnable = $Datahelper->getStoreConfigValue('booking/booking_config/show_calendar');
?>
<div class="modal-header">
	<h1 class="modal-room-title"><?php echo $title;?></h1>
</div>
<div class="modal-body">
<div class="page-layout-1column">	
	<div class="product-info-main">
			<form action="<?php echo $CartUrl; ?>" method="post" id="product_addtocart_form" enctype="multipart/form-data">
			<input type="hidden" name="product" value="<?php echo $productId; ?>" />
			<input type="hidden" name="selected_configurable_option" value="" />
			<input type="hidden" name="related_product" id="related-products-field" value="" />
			<input type="hidden" name="form_key" id="form-key" value="<?php echo $FormKey->getFormKey();?>" />
			<input type="hidden" id="price" name="price" value="<?php echo $price;?>"></input>
			<input type="hidden" id="room_id" name="room_id" value="<?php echo $roomId;?>"></input>
			<input type="hidden" id="booking-type" name="booking-type" value="<?php echo __('hotel');?>"/>
			<input type="hidden" id="room-title" name="room-title" value="<?php echo $title;?>"/>
			<input type="hidden" id="room-category" name="room-category" value="<?php echo $roomCategory;?>"/>
			

	<?php /************Start**********/ ?>

	<div class="product-options-wrapper">
	<div class="fieldset" id="book_date_range">
	 	<div class="field">
            <label class="label" for="book-room-check-in">
                <span>Check In</span>
            </label>
            <div class="control">
				<input type="text" autocomplete="off" id="book-room-check-in" name="check-in" value="" readonly="true"></input>
            </div>
        </div>


		<div class="field">
            <label class="label" for="book-room-check-out">
                <span>Check Out</span>
            </label>
            <div class="control">
				<input type="text" autocomplete="off" id="book-room-check-out" name="check-out" value="" readonly="true"></input>
            </div>
        </div>


        <div class="field">
            <label class="label" for="room-qty">
                <span>Quantity</span>
            </label>
            <div class="control">
               <select class="selected_room_numbers" id="room-qty" name="qty">
					<?php for ($i=1;$i<=count(array_unique($countRoomNumbers)); $i++) { ?>
						<option value="<?php echo $i;?>"><?php echo $i; ?></option>
					<?php } ?>
					</select>

            </div>
        </div>

		<div class="field">
			<div id="rooms-availability"></div>
		</div>

		<div class="field">
            <label class="label" for="room-price">
                <span>Price</span>
            </label>
            <div class="control">
               <span><?php echo $currencySymbol->Currency($price);?></span>
            </div>
        </div>
		
    <div class="product-options-bottom">
   	 <div class="box-tocart">

        <div class="actions">
            <input type="button"class="action subscribe primary"   value="<?php echo __('Check Availability');?>" id="check-availablity"></input>
        </div>
       </div>
     </div>

		<div class="field">
			<div id="availability-info"></div>
		</div>

	</div>
	</div>	

			<?php /************End**********/ ?>
			<?php
				echo $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View')->setTemplate('Ced_Booking::product/view/addtocart.phtml')->toHtml();
			?>
		</form>
	</div>	

	<div class="product media">
		<?php echo $block->getLayout()->createBlock('Ced\Booking\Block\Product\View\Gallery')->setData( ['images' => $roomImages])->setTemplate('Ced_Booking::product/view/gallery.phtml')->toHtml(); ?>
	</div>
</div>
<div style="clear: both;"></div>



		<?php /********************** Room Description ************************/?>

		<div id="room-desc">
			<h3><?php echo __('Room Description'); ?></h3>
			<div class="container room-info-wrapper">
				<?php if ($roomDesc == '') : ?>
					<div class="message info empty"><span><?php echo __('Empty Description'); ?>.</span></div>
				<?php else : ?>
					<p><?php echo $roomDesc; ?></p>
				<?php endif; ?>
			</div>
		</div>



<div style="clear: both;"></div>


		<?php /********************** Room Amenities ************************/?>


<div id="room-facilities">
	<h3><?php  echo __('Room Facilities'); ?></h3>
    <div class="container" id="facility-wrapper">
        <div class="row">
          	<div class="wrapper">
              	<div id="owl-facilities-room">
              	<?php if (count($roomAmenities)) : ?>
              	<?php foreach ($roomAmenities as $facility) :
              			foreach ($facilities as $val) :
              				if ($val->getId() == $facility->getAmenityId()) : ?>
			                    <div class="item">
			                    	<?php if (preg_match('/fa-/',$val->getImage()) || preg_match('/im-/',$val->getImage())) { 

			                    		$icon_class = explode('-', $val->getImage() ); 
										$type_font = $icon_class[0]; ?>

										<i title="<?php echo $val->getTitle();?>" class="ace-icon <?php echo $type_font.' '; ?><?php echo $val->getImage(); ?> fa-5x" ></i>
			                    	<?php } elseif ($val->getImage() == '') { ?>
			                    		<img title="<?php echo $val->getTitle();?>" src="<?php echo $this->getViewFileUrl('Magento_Catalog::images/product/placeholder/image.jpg');?>" alt="Owl Image">
			                    	<?php } else { ?>
			                    		<img title="<?php echo $val->getTitle();?>" src="<?php echo $block->getUrl().'pub/media/'.$val->getImage();?>" alt="Owl Image">
			                    	<?php } ?>
                                </div>
              	<?php endif;
              		  endforeach;
              		  endforeach;
              		  else : ?>
              	<div class="message info empty"><span><?php echo __('No Facilities in this room'); ?>.</span></div>
              	<?php endif;?>
              	</div>
            </div>
          </div>
    </div>
</div>


<div class="col-2">

	<div class="col room-information">
		<?php /**************************  Guest Allowed **************************/ ?>

		<div id="room-allowed-guest">
			<h3><?php echo __('Allowed Guests'); ?></h3>
			<div class="container room-info-wrapper">
				<div>
					<span class='room-info-label'><?php echo __('Maximum allowed Adults: '); ?></span>
					<span><?php echo $maxAllowedAdults; ?></span>
				</div>
				<div>
					<span class='room-info-label'><?php echo __('Maximum allowed Childrens: '); ?></span>
					<span><?php echo $maxAllowedchild; ?></span>
				</div>
			</div>
		</div>


		<?php /**************************  Room Other Information **************************/ ?>

		<div id="room-allowed-guest">
			<h3><?php echo __('Other Information'); ?></h3>
			<div class="container room-info-wrapper">
				<div>
					<span class='room-info-label'><?php echo __('Room Type: '); ?></span>
					<span><?php echo $title; ?></span>
				</div>
				<div>
					<span class='room-info-label'><?php echo __('Room Category: '); ?></span>
					<span><?php echo $roomCategory; ?></span>
				</div>
				<div>
					<span class='room-info-label'><?php echo __('Check-In: '); ?></span>
					<span><?php echo $product->getBookingCheckInTime(); ?></span>
				</div>
				<div>
					<span class='room-info-label'><?php echo __('Check-Out: '); ?></span>
					<span><?php echo $product->getBookingCheckOutTime(); ?></span>
				</div>
			</div>
		</div>
	</div>
	<?php if ($isCalendarEnable) : ?>
    <div class="col">
            <h3><?php /* @escapeNotVerified */ echo __('Booking Availability'); ?></h3>
              <div id='booking_calendar'></div>
    </div>
    <?php endif; ?>
</div> 
<?php if (!$isCalendarEnable) : ?>
	<style>
		.room-information {
		  	width: 100% !important;
		}
	</style>
<?php else : ?>
	<style>
		.room-information {
		  	width: 50% !important;
		}
	</style>
<?php endif; ?>
<script>

require([
    'jquery',
    'ced_fullcalendar'
    ], function($, fullCalendar){ 



    


    $('#booking_calendar').fullCalendar({
      editable: false,
      eventLimit: true, // allow "more" link when too many events
      dragScroll:false,
      cache: true,

       eventSources: [

        // your event source
        {
            url: '<?php echo $this->getUrl('booking/booking/checkCalendarBooking'); ?>',
            type: 'POST',
            showLoader: true,
            cache: true,

            data: {
                product_id: '<?php echo $this->getProductId() ?>',
                max_qty: '<?php echo count(array_unique($countRoomNumbers)) ?>',
                attribute_set_id: '<?php echo $this->getProduct()->getAttributeSetId() ?>',
                room_id: '<?php echo $roomId; ?>',
            },
            error: function() {
                alert('there was an error while fetching events!');
            },
            
        }

        // any other sources...

    ]


    });
    
  });


require([
			'jquery',
			"jquery/ui",
		],
	function ($,jqueryUi){

		$('#book-room-check-in').val($('#room-check-in').val());
		$('#book-room-check-out').val($('#room-check-out').val());

	 	var dateToday = new Date();

  		$( "#book-room-check-in, #book-room-check-out" ).datepicker({
			minDate: dateToday,
			dateFormat: "yy-mm-dd",
			onSelect: function( selectedDate, inst) {
				$('#product-addtocart-button').prop('disabled',true);
				var date = jQuery.datepicker.parseDate(inst.settings.dateFormat || jQuery.datepicker._defaults.dateFormat, selectedDate, inst.settings);
				var dateText = jQuery.datepicker.formatDate("yy-mm-dd", date, inst.settings);
				if(this.id == "book-room-check-in"){										
					date.setDate(date.getDate() + 1);
					jQuery("#book-room-check-out" ).datepicker( "option", "minDate", date );
				}
			}
		});

	$('.room-qty').change(function(){

		$('#product-addtocart-button').prop('disabled',true);
	});

	    var html='';
	    $('.selected_room_numbers').on('change',function(){

	    	var rooms = JSON.parse($('#available-rooms').val()); 

	    	if ($('.selected_room_numbers').val() > Object.keys(rooms).length) {

	    		$('#product-addtocart-button').prop('disabled',true);

	    		if (Object.keys(rooms).length > 1) {

	    			html = '<div>'+Object.keys(rooms).length+' rooms available.</div>';
	    		} 
	    		if (Object.keys(rooms).length == 1) {

	    			html = '<div>'+Object.keys(rooms).length+' room available.</div>';
	    		}
	    		
	    	} else {
	    		$('#product-addtocart-button').prop('disabled',false);
	    	}
	    	$('#rooms-availability').html('');
	    	$('#rooms-availability').append(html);
	    	
	    });
	   

	    $('#check-availablity').click(function(){

	    	var checkIn = $('#book-room-check-in').val();
	    	var checkOut = $('#book-room-check-out').val();
	    	var qty = $('.selected_room_numbers').val();
	    	var roomId = $('#room_id').val();
	    	var price = $('#price').val();

	    	$.ajax({
				url : '<?php echo $checkAvailbilityUrl; ?>',
				dataType : 'json',
				type : 'POST',
				data : {check_in:checkIn,check_out:checkOut,qty: qty,room_id: roomId,price:price},
				showLoader: true,
				success : function(res)
				{
					$('#availability-info').html(res.template);
				},
				error : function()
				{
					
				}
			}); 
	 	
	 	});
	
});
</script>
