<?php

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the 
 * You can check the licence at this URL: http://cedcommerce.com/license-agreement.txt
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Booking
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license      http://cedcommerce.com/license-agreement.txt
 */
?>
	<div class="row">
		<!--
		<div class="col-lg-12">
			<h1 class="page-header"><?php echo __('Dashboard') ?></h1>
		</div>
		-->
		<!-- /.col-lg-12 -->
	</div>
	<div class="row">
		<?php // echo $block->getMessagesBlock()->getGroupedHtml() ?>
	</div>
	<div class="row">
		<div class="col-lg-12">
			<p class="hello"><strong><?php  echo __('Hello,') ?></strong></p>
			<p><?php echo __('From your Dashboard you have the ability to view a snapshot of your total bookings , total sales , total booking country wise, booking statistics (week, month or year wise) and recent activity on your associated bookable products.') ?></p>
		</div>
	</div>
	<div class="row">
		<?php  echo $block->getChildHtml('admin_booking_info') ?>
	</div> 
	
	<div class="row">
		
			<div class="col-lg-12">
				<?php  echo $block->getChildHtml('calendar_booking') ?>
			</div>
			
	</div>