<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\ConfigurableProduct\Block\Adminhtml\Product\Steps\SelectAttributes */
$param = $this->getRequest()->getParams();
$roomId = isset($param['Room_Id']) ? $param['Room_Id'] : '';
?>
<div class="select-attributes-block <?= /* @noEscape */ $block->getData('config/dataScope') ?>" data-role="select-attributes-step">

    <h2 class="steps-wizard-title"><?php echo $block->escapeHtml(
            __('Step 1: Fill the General Form')
        ); ?></h2>
</div>
<?= $block->getChildHtml(); ?>
<?php if ($roomId!='') : ?>
<input type='hidden' value='<?php echo $roomId; ?>' id='edit_room_id'></input>
<?php endif; ?>
<input type='hidden' value='<?php echo $block->getRoomsCollection(); ?>' id='booking_rooms_json_data'></input>
 <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= /* @noEscape */  $block->getComponentName()?>": {
                        "component": "Ced_Booking/js/variations/steps/generalform",
                        "appendTo": "<?= /* @noEscape */  $block->getParentComponentName()?>"
                    }
                }
            }
        }
    }
</script> 
 