<div class="top-banner"> 
	<img src="<?php echo $this->getUrl('pub/media/booking/store/banner'); ?>banner-1.jpg" /> 
	<div>
		<h3>All Purpose Booking Solution</h3>
		<p>Book any type of bookable product with one single extension. Just install this simple extension on your magento 2 store and you can add any types of the booking on your magento store. Easily add <strong>Hotel Booking</strong>, <strong>Daily Rent Booking</strong> and <strong>Hourly Rent</strong> booking products on magneto store.</p>
	</div>
</div>


<div class="booking-features">
	<h3>Features-</h3>
	<ul>
		<li>All purpose booking solution</li>
		<li>Add Hotels and Rooms in booking listing</li>
		<li>Exclude days in which service not available</li>
		<li>Add multiple numbers of hotel room as per category</li>
		<li>Add Daily type rent product</li>
		<li>Add Hourly types of the rent product</li>
		<li>Admin full control on the booking</li>
	</ul>
</div>

<?php $links =  $this->getAllNavLinks(); print_r($links); ?>
<div class="small-banners col-3">
	<div class="col">
		<a href="">
			<img src="<?php echo $this->getUrl('pub/media/booking/store/banner'); ?>small-banner3.jpg" /> 
			<span>Book Hotels</span>
		</a>
	</div>
	<div class="col">
		<a href="">
			<img src="<?php echo $this->getUrl('pub/media/booking/store/banner'); ?>small-banner2.jpg" /> 
			<span>Daily Bookings</span>
		</a>
	</div>
	<div class="col">
		<a href="">
			<img src="<?php echo $this->getUrl('pub/media/booking/store/banner'); ?>small-banner1.jpg" /> 
			<span>Hourly Hotels</span>
		</a>
	</div>
</div>